spring:
  datasource:
    username: localdev
    password: localdev_password
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5431/approved_premises_localdev
  flyway:
    locations: classpath:db/migration/all,classpath:db/migration/local+dev+test,classpath:db/migration/local,classpath:db/migration/all-except-integration
  jpa:
    database: postgresql
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
      password: ""
  output:
    ansi:
      enabled: ALWAYS

hmpps.sqs:
  provider: localstack
  topics:
    domainevents:
      arn: arn:aws:sns:eu-west-2:000000000000:domainevents

domain-events:
  cas1:
    emit-enabled: true
    async-save-enabled: false
  cas2:
    emit-enabled: true
    async-save-enabled: false
  cas3:
    emit-enabled: bookingCancelled,bookingConfirmed,bookingProvisionallyMade,personArrived,personDeparted,referralSubmitted,personDepartureUpdated,bookingCancelledUpdated,personArrivedUpdated
    async-save-enabled: false

log-client-credentials-jwt-info: true
log-request-response: true

seed:
  file-prefix: "./seed"
  auto:
    enabled: true
    file-prefixes: classpath:db/seed/local+dev+test
  auto-script:
    cas1-enabled: true
    cas2-enabled: true
    noms: A1234AI

assign-default-region-to-users-with-unknown-region: true
preemptive-cache-logging-enabled: true
preemptive-cache-lock-duration-ms: 60000

user-allocations:
  rules:
    esap-assessments:
      allocate-to-user: JIMSNOWLDAP

feature-flags:
  get-documents-from-ap-delius: true
  get-offences-from-ap-delius: true


logging:
  level:
    # Log hibernate queries
    org.hibernate.SQL: DEBUG
    # Uncomment the two entries below to see SQL binding
    #org.hibernate.orm.jdbc.bind: TRACE
    # allows us to see the JWT token to simplify local API invocation
    uk.gov.justice.digital.hmpps.approvedpremisesapi.config.RequestResponseLoggingFilter: TRACE
    # allows us to see the request URL and method for upstream requests
    reactor.netty.http.client.HttpClientConnect: DEBUG
